CREATE TABLE bbs.comment
(id INTEGER AUTO_INCREMENT PRIMARY KEY
,user_id INTEGER(11) NOT NULL
,message_id INTEGER(11) NOT NULL
,text VARCHAR(500)NOT NULL
,insert_date TIMESTAMP NOT NULL
,update_date TIMESTAMP NOT NULL
);