CREATE TABLE bbs.postmessage
(id INTEGER AUTO_INCREMENT PRIMARY KEY
,user_id INTEGER(11) NOT NULL
,title VARCHAR(50)NOT NULL
,text VARCHAR(1000)NOT NULL
,category VARCHAR(10)NOT NULL
,insert_date TIMESTAMP NOT NULL
,update_date TIMESTAMP NOT NULL
);